#! /usr/bin/python3

import re
import threading
from threading import Thread
from queue import Queue
from concurrent.futures import ThreadPoolExecutor, as_completed
import time
import shutil
import gi
try:
    gi.require_version('WebKit2', '4.1')
    gi.require_version('Gtk', '3.0')
except:
    gi.require_version('WebKit2', '4.0')

from gi.repository import WebKit2, Gtk, Gio, Gdk, GLib
import json
import webbrowser
import urllib.error
import urllib.request
import sys
import subprocess
import signal
import os
import inspect

try:
    import distro
except:
    import platform


# global variable - path inc the suffix / of where the app is being executed
start_location = "./"  # path defined on app startup

win = None

def versiontuple(v):
    return tuple(map(int, (v.split("."))))


class AppView(WebKit2.WebView):

    def __init__(self):
        WebKit2.WebView.__init__(self)

        self.connect('load-changed', self._load_changed_cb)
        self.connect('notify::title', self._title_changed_cb)
        self.connect('context-menu', self._context_menu_cb)

        self.l_uri = None
        self.back_btn = None
        self.page_title = None

        self.back_signal_handler = None

    def _back_action(self, data):
        if systemstate.check_control_file_exists():
            message = "<div class=\"text-md-center\">"
            message += "<strong>Codec-Multimídia</strong><br>"
            message += "<br><br> Atenção"
            message += "<br><br>Um processo está em execução no momento. Por favor, espere até que ele seja concluído antes de fechar ou sair."
            message += "</div>"

            popup = PopupMessage(message, PopupMessage.INFO)

            popup.showMessage()
            return True
        
        if "category.html" in app.last_page and "application.html" in app.current_page:
            app.run_javascript(f'smoothPageFade({app.last_page})')
            app.last_page = app.current_page
        else:
            app.run_javascript("smoothPageFade('index.html')")
            app.last_page = app.current_page

    def _index_action(self, data):
        app.run_javascript("backAction()")

    def _push_config(self):
        current_page = app.current_page.replace(".html", "")

        if "?" in current_page:
            current_page = current_page.replace("?", "")

        # Dynamically toggle header controls button
        if current_page != "index":
            if not self.back_btn.is_sensitive():
                self.back_signal_handler = self.back_btn.connect("clicked", self._back_action)
        else:
            if self.back_signal_handler:
                self.back_btn.disconnect(self.back_signal_handler)
                self.back_signal_handler = None

        app.update_page('.normal-session-only', 'show')

        if systemstate.is_online:
            app.run_javascript("$('.offline').hide()")
        else:
            app.run_javascript("$('.offline').show()")

        distroname = "Debian 12"
        app.run_javascript(
            "$('span[name=\"distro-name\"]').html('{}')".format(distroname))

        # Apply intermediate actions, if any are present
        if current_page in systemstate.intermediate_actions:
            for action in systemstate.intermediate_actions[current_page]:
                app.update_page(action[0], action[1], action[2], action[3])

    def _load_changed_cb(self, view, frame):
        uri = str(self.get_uri())

        try:
            app.current_page = uri.rsplit('#')[0].rsplit('/', 1)[1]
            self._push_config()
        except IndexError as e:
            dbg.stdout("_load_changed_cb", "weird uri " + uri, 0, 1)

    def _title_changed_cb(self, view, frame):
        title = self.get_title()

        # An empty command get executed while toggling startup
        # option. Actual reason for this command execution needs
        # to be investigated.
        if title == '':
            return

        self._do_command(title)

        # Clear title after executing a command. Otherwise, if the same
        # command is executed with another event, it won't be identified
        # as there is no effective title change. Consider links in applets
        # page.
        app.run_javascript("document.title = ''")

    def _context_menu_cb(self, webview, menu, event, htr, user_data=None):
        # Disable context menu.
        return True

    def _do_command(self, uri):
        if uri.startswith("title?"):
            title = uri[6:]
            self.page_title.set_label(title)
        elif uri == 'about':
            distroname = "Debian 12"
            message = "<div class=\"text-md-center\">"
            message += "<strong>Codec-Multimídia</strong><br>"
            message += "Versão {}".format(
                systemstate.app_version
            )
            message += "<br><br> Policorp Tecnolgia Ltda"
            message += "<br><br>Policorp Linux ({})".format(
                distroname
            )

            message += "</div>"

            popup = PopupMessage(message, PopupMessage.INFO)

            popup.showMessage()
        elif uri == 'check-init-main':
            systemstate.remove_control_file()
        elif 'category-' in uri:
            category_name = uri.partition("category-")[2]
            systemstate.create_category_page(self, category_name)
        elif 'app-' in uri:
            systemstate.create_app_page(self)
        elif 'flatpak-install' in uri:
            systemstate.create_control_file()
            if not codecmanager.isNetworkConnected():
                systemstate.remove_control_file()
                app.run_javascript("document.getElementById('pgr_install_app').classList.remove('d-block');")
                app.run_javascript("document.getElementById('pgr_install_app').classList.add('d-none');")
                app.run_javascript("document.getElementById('btn_install_app').disabled = false;")
                app.run_javascript("setCursorNormal();")
                message = "<div class=\"text-md-center\">"
                message += "<strong>Codecs Multimídia</strong><br>"
                message += "<br><br> Atenção"
                message += "<br><br>Sem conexão com a internet. Verifique se o cabo está conectado ou se você está conectado a uma rede Wi-Fi."
                message += "</div>"
                popup = PopupMessage(message, PopupMessage.INFO)
                popup.showMessage()
            else:
                codecmanager.installApp()
        elif 'flatpak-remove' in uri:
            systemstate.create_control_file()
            if codecmanager.isNetworkConnected():
                    codecmanager.initRemoveApp()
            else:
                systemstate.remove_control_file()

                app.run_javascript("document.getElementById('pgr_install_app').classList.remove('d-block');")
                app.run_javascript("document.getElementById('pgr_install_app').classList.add('d-none');")
                app.run_javascript("document.getElementById('btn_open_app').disabled = false;")
                app.run_javascript("document.getElementById('btn_remove_app').disabled = false;")
                app.run_javascript("setCursorNormal();")

                message = "<div class=\"text-md-center\">"
                message += "<strong>Codecs Multimídia</strong><br>"
                message += "<br><br> Atenção"
                message += "<br><br>Sem conexão com a internet. Verifique se o cabo está conectado ou se você está conectado a uma rede Wi-Fi."
                message += "</div>"

                popup = PopupMessage(message, PopupMessage.INFO)

                popup.showMessage()
        else:
            print('Unknown command: {}'.format(uri))


class Debug(object):
    def __init__(self):
        self.verbose_level = 0

    def stdout(self, item, info, verbosity=0, colour=0):
        # Only colourise output if running in a real terminal.
        if sys.stdout.isatty():
            end = '\033[0m'
            if colour == 1:  # Failure (Red)
                start = '\033[91m'
            elif colour == 2:  # Success (Green)
                start = '\033[92m'
            elif colour == 3:  # Action (Yellow)
                start = '\033[93m'
            elif colour == 4:  # Debug (Blue)
                start = '\033[96m'
            else:  # Normal/Misc (White)
                start = '\033[0m'

        # Ignore colours when redirected or piped.
        else:
            start = ''
            end = ''

        # Output the message depending how detailed it is.
        if verbosity <= self.verbose_level:
            print(start + '[' + item + '] ' + info, end)


class PopupMessage(object):
    ERROR = 0
    CONFIRMATION = 1
    STATUS = 2
    INFO = 3

    def __init__(self, message, type, details=None, actions=dict(OK='removeSlowly(\'#popup-message-window\')')):
        '''
         message => Message to user
         type => Type of message(error, confirmation ..etc)
        '''
        self.details = details
        self.message = message
        self.type = type
        self.actions = actions

    def showMessage(self):
        # Remove message window if already exists
        app.update_page('#popup-message-window', 'remove')

        # Dynamically inject Popup message window
        app.update_page('#wrapper', 'append', '<div id="popup-message-window">\
        <div id="popup-message-container">\
        </div>\
      </div>')

        app.update_page('#popup-message-container', 'append', '<p id="popup-message">' +
                        self.message + '</p>')
        if self.type == PopupMessage.ERROR and self.details:
            app.update_page('#popup-message-container', 'append',
                            '<textarea id="details">' + self.details + '</textarea>')
        elif self.type == PopupMessage.STATUS:
            html_table = '<table class="table table-bordered table-condensed">'
            html_table += '<thead><th>TASK</th><th>NAME</th><th>STATUS</th></thead>'
            for task in self.details:
                html_table += '<tr>'
                html_table += '<td>{}</td><td>{}</td><td>{}</td>'.format(
                    task[0], task[1], task[2])
            html_table += '</table>'

            html_table = '<div id="status-table-container">' + html_table + '</div>'

            app.update_page('#popup-message-container', 'append', html_table)
        elif self.type == PopupMessage.INFO:
            pass  # Message is already added
        else:
            dbg.stdout(self.type, 'message is not handled yet', 3)

        buttons = ''

        for action in self.actions:
            buttons += '<a class="btn btn-primary" onclick="' + self.actions[
                action] + ';document.title=\'\'">&emsp;' + action + '&emsp;</a>&emsp;'

        app.update_page('#popup-message-container', 'append',
                        '<div class="text-md-right">' + buttons + '</div>')
        app.update_page('#popup-message-window', 'fadeIn')


class CodecManager:
    def __init__(self):
        self.appName = None
        self.appId = None
        self.queue = Queue()

    def isNetworkConnected(self):
        def run_ping():
            host = "8.8.8.8"  # Usando o IP do Google DNS que é confiável para verificar a conectividade
            try:
                result = subprocess.run(
                    ["ping", "-c", "1", host],
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                    timeout=5  # Timeout para garantir que o ping não fique preso
                )
                if result.returncode == 0:
                    return True
                else:
                    return False
            except Exception:
                return False

        with ThreadPoolExecutor(max_workers=1) as executor:
            future = executor.submit(run_ping)
            is_connected = future.result()

        return is_connected

    def checkDiskSize(self):
        total, used, free = shutil.disk_usage("/")
        min_size_bytes = 1 * 1024**3 

        if free > min_size_bytes:
            return True
        else:
            return False

    def openGnomeSoftware(self):
        try:
            subprocess.Popen(['gnome-software'], start_new_session=True)
            return True
        except subprocess.CalledProcessError:
            print(f"Failed to run ")
        
        return False


    def isCodecInstalled(self):
        try:
            result = subprocess.run(
                ['dpkg', '-l'],
                capture_output=True,
                text=True,
                check=True
            )

            return 'gstreamer1.0-plugins-bad' in result.stdout
        except FileNotFoundError:
            return False
        except subprocess.CalledProcessError:
            return False

    def checkFlathubRepo(self):
        try:
            # Executa o comando `flatpak remotes` e captura a saída
            result = subprocess.run(['flatpak', 'remotes'], capture_output=True, text=True, check=True)
            
            # Verifica se "flathub" está presente na saída do comando
            if 'flathub' in result.stdout:
                print("O repositório Flathub já está adicionado.")
                return True
            else:
                print("O repositório Flathub não está adicionado.")
                return False
        except Exception as e:
            print(f"Erro ao executar o comando `flatpak remotes`: {e}")
            return False

    def addFlathubRepo(self):
        try:
            # Adiciona o repositório Flathub usando o comando `flatpak remote-add`
            subprocess.run(['flatpak', 'remote-add', '--user', '--if-not-exists', 'flathub', 'https://flathub.org/repo/flathub.flatpakrepo'],
                        check=True)
            print("Repositório Flathub adicionado com sucesso.")
        except subprocess.CalledProcessError as e:
            print(f"Erro ao adicionar o repositório Flathub: {e}")

    def openApp(self):
        try:
            # Execute the flatpak run command
            subprocess.Popen(["flatpak", "run", self.appId], start_new_session=True)

            app.run_javascript("document.getElementById('btn_open_app').disabled = false;")
            app.run_javascript("document.getElementById('btn_remove_app').disabled = false;")
            app.run_javascript("setCursorNormal();")
            
            return True
        except subprocess.CalledProcessError:
            print(f"Failed to run {self.appId}")
        
        return False

    def isAppInstaled(self):
        result = subprocess.run(["flatpak", "list"], capture_output=True, text=True)
        output = result.stdout

        if self.appId in output:
            return True
        
        return False


    def removeApp(self):
        try:
            # Read the list of packages from codecs.txt
            with open('/usr/share/policorp-codecs/codecs.txt', 'r') as file:
                packages = file.read().splitlines()

            if not packages:
                print("No packages found to remove.")
                return False

            # Combine all packages into one remove command
            remove_command = " ".join(packages)
            combined_command = f"apt-get remove -y {remove_command} && apt-get autoremove -y"

            # Run the combined command with pkexec
            command = ["pkexec", "sudo", "bash", "-c", combined_command]
            process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)

            for line in iter(process.stdout.readline, ''):
                print(line.strip())
                self.queue.put(line.strip())  # Add the line to the queue
                time.sleep(0.1)

            # Wait for the process to complete
            process.wait()

            # Check if there was an error
            stderr_output = process.stderr.read()
            if "error" in stderr_output.lower():
                print(f"Error during removal and autoremove: {stderr_output}")
                return False

            # Check for successful completion messages
            return True

        except Exception as e:
            print(f"An unexpected error occurred: {e}")
            return False

    def initRemoveApp(self):
        def remove_process():
            result = self.removeApp()
            if result:
                systemstate.remove_control_file()

                app.run_javascript("document.getElementById('pgr_install_app').classList.remove('d-block');")
                app.run_javascript("document.getElementById('pgr_install_app').classList.add('d-none');")
                app.run_javascript("document.getElementById('btn_install_app').classList.remove('d-none');")
                app.run_javascript("document.getElementById('btn_install_app').classList.add('d-block');")
                app.run_javascript("document.getElementById('btn_open_app').classList.remove('d-block');")
                app.run_javascript("document.getElementById('btn_open_app').classList.add('d-none');")
                app.run_javascript("document.getElementById('btn_open_app').disabled = false;")
                app.run_javascript("document.getElementById('btn_remove_app').classList.remove('d-block');")
                app.run_javascript("document.getElementById('btn_remove_app').classList.add('d-none');")
                app.run_javascript("document.getElementById('btn_remove_app').disabled = false;")
                app.run_javascript("setCursorNormal();")

                self.queue.put("Codecs Removidos com sucesso.")
                message = "<div class=\"text-md-center\">"
                message += "<strong>Codec-Multimidia</strong><br>"
                message += "<br><br> Informação"
                message += "<br><br> Os codecs foram removidos com sucesso"
                message += "</div>"

                popup = PopupMessage(message, PopupMessage.INFO)

                popup.showMessage()
            else:
                systemstate.remove_control_file()

                app.run_javascript("document.getElementById('pgr_install_app').classList.remove('d-block');")
                app.run_javascript("document.getElementById('pgr_install_app').classList.add('d-none');")
                app.run_javascript("document.getElementById('btn_open_app').disabled = false;")
                app.run_javascript("document.getElementById('btn_remove_app').disabled = false;")
                app.run_javascript("setCursorNormal();")

                message = "<div class=\"text-md-center\">"
                message += "<strong>Erro de Permissão</strong><br>"
                message += "<br><br> Atenção"
                message += "<br><br> Tente novamente para excluir os pacotes de codec."
                message += "</div>"

                popup = PopupMessage(message, PopupMessage.INFO)

                popup.showMessage()

        ui_update_thread = threading.Thread(target=self.update_ui_thread)
        ui_update_thread.start()

        t = Thread(target=remove_process)
        t.start()
 
    def update_ui_thread(self):
        while True:
            try:
                message = self.queue.get(timeout=1)  # Tenta pegar uma mensagem da fila
                if message:
                    message = message.replace("\n", " ")
                    app.update_page('#lbl_log', 'html', message)
            except Exception as e:
                pass  # Nenhuma mensagem foi encontrada na fila


    def installApp(self):
        systemstate.remove_control_file()

        def install():
            try:
                # Read all packages from codecs.txt
                with open('/usr/share/policorp-codecs/codecs.txt', 'r') as file:
                    packages = [line.strip() for line in file if line.strip()]

                if not packages:
                    self.queue.put("No packages found to install.")
                    return

                # Combine all package names into one install command
                packages_str = ' '.join(packages)
                command = f"apt-get install -y {packages_str} && apt-get autoremove -y"

                # Run the combined command with pkexec
                pkexec_command = ["pkexec", "sudo", "bash", "-c", command]
                process = subprocess.Popen(pkexec_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

                # Read stdout and stderr line by line
                for stdout_line in iter(process.stdout.readline, ''):
                    self.queue.put(stdout_line.strip())  # Put stdout line into the queue
                for stderr_line in iter(process.stderr.readline, ''):
                    self.queue.put(stderr_line.strip())  # Put stderr line into the queue

                process.stdout.close()
                process.stderr.close()
                process.wait()

                if process.returncode == 0:
                    self.queue.put("Codecs foram instalados.")
                    self.update_ui_after_installation()
                else:
                    self.queue.put("Ocorreu algum erro durante a instalação")
                    systemstate.remove_control_file()

                    app.run_javascript("document.getElementById('pgr_install_app').classList.remove('d-block');")
                    app.run_javascript("document.getElementById('pgr_install_app').classList.add('d-none');")
                    app.run_javascript("document.getElementById('btn_open_app').disabled = false;")
                    app.run_javascript("document.getElementById('btn_install_app').disabled = false;")
                    app.run_javascript("setCursorNormal();")

                    message = "<div class=\"text-md-center\">"
                    message += "<strong>Erro de Permissão</strong><br>"
                    message += "<br><br> Atenção"
                    message += "<br><br> Tente novamente para instalar os pacotes de codec."
                    message += "</div>"
                    popup = PopupMessage(message, PopupMessage.INFO)

                    popup.showMessage()


            except FileNotFoundError:
                self.queue.put("The file codecs.txt was not found.")
            except Exception as e:
                self.queue.put(f"An unexpected error occurred: {e}")

        # Start UI update thread
        ui_update_thread = threading.Thread(target=self.update_ui_thread)
        ui_update_thread.start()

        # Start installation thread
        install_thread = threading.Thread(target=install)
        install_thread.start()
        
    def update_ui_after_installation(self):
        # UI updates after installation
        app.run_javascript("setCursorNormal();")
        app.run_javascript("document.getElementById('pgr_install_app').classList.remove('d-block');")
        app.run_javascript("document.getElementById('pgr_install_app').classList.add('d-none');")
        app.run_javascript("document.getElementById('btn_remove_app').classList.remove('d-none');")
        app.run_javascript("document.getElementById('btn_remove_app').classList.add('d-block');")
        app.run_javascript("document.getElementById('btn_install_app').classList.remove('d-block');")
        app.run_javascript("document.getElementById('btn_install_app').classList.add('d-none');")
        app.run_javascript("document.getElementById('btn_install_app').disabled = false;")
        message = "<div class=\"text-md-center\">"
        message += "<strong>Codecs-Multimidia</strong><br>"
        message += "<br><br> Informação"
        message += "<br><br>Os Codecs foram instalados com sucesso."
        message += "</div>"

        popup = PopupMessage(message, PopupMessage.INFO)
        popup.showMessage()

class SystemState(object):

    def __init__(self):
        self.home_dir = os.path.expanduser('~')
        self.config_dir = os.path.join(self.home_dir, '.config')
        self.control_store_file = os.path.join(self.config_dir, 'controlCodecs')

        # Set default variables
        self.is_online = False
        self.updates_subscribed = False
        self.app_version = '2.0'
        self.first_run = False
        self.graphics_vendor = 'Unknown'
        self.graphics_grep = 'Unknown'
        self.scale_factor = 0

        # Full path to binary
        self._store_bin_path = os.path.abspath(
            inspect.getfile(inspect.currentframe()))

        # Get current architecture of system.
        self.arch = str(
            subprocess.Popen(['dpkg', '--print-architecture'], stdout=subprocess.PIPE).communicate()[0]).strip('\\nb\'')

        self.session_type = 'normal'

        # To inform the user if they are running in BIOS or UEFI mode.
        if os.path.exists("/sys/firmware/efi"):
            self.boot_mode = 'UEFI'
        else:
            self.boot_mode = 'BIOS'

        # Multithread to prevent holding up program execution.
        Thread(target=self.detect_graphics).start()

        # Retain some show/hide actions applied while changing page.
        # This is specially required when page change happens while
        # installation/removal is in progress.
        self.intermediate_actions = {}

    def create_control_file(self):
        try:
            os.makedirs(self.config_dir, exist_ok=True)
            control_file_path = os.path.join(self.config_dir, self.control_store_file)
            with open(control_file_path, 'a'):
                pass
        except Exception as e:
            print(f"Erro ao criar o arquivo: {e}")

    def remove_control_file(self):
        if os.path.exists(self.control_store_file):
            os.remove(self.control_store_file)
        else:
            pass

    def check_control_file_exists(self):
        if os.path.exists(self.control_store_file):
            return True
        else:
            return False
    
    def addIntermediateActions(self, filename, actions):

        if filename not in self.intermediate_actions:
            self.intermediate_actions[filename] = []

        self.intermediate_actions[filename] += actions

    def removeIntermediateActions(self, filename, actions):

        for action in actions:
            self.intermediate_actions[filename].remove(action)

        if len(self.intermediate_actions[filename]) == 0:
            del self.intermediate_actions[filename]
    
    def detect_graphics(self):
        # TODO: Support dual graphic cards.
        dbg.stdout('Specs', 'Detecting graphics vendor... ', 1, 3)
        try:
            output = subprocess.Popen(
                'lspci | grep VGA', stdout=subprocess.PIPE, shell='True').communicate()[0]
            output = output.decode(encoding='UTF-8')
        except:
            # When 'lspci' does not find a VGA controller (this is the case for the RPi 2)
            dbg.stdout(
                'Specs', "Couldn't detect a VGA Controller on this system.", 0, 1)
            output = 'Unknown'

        # Scan for and set known brand name.
        if output.find('NVIDIA') != -1:
            self.graphics_vendor = 'NVIDIA'
        elif output.find('AMD') != -1:
            self.graphics_vendor = 'AMD'
        elif output.find('Intel') != -1:
            self.graphics_vendor = 'Intel'
        elif output.find('VirtualBox') != -1:
            self.graphics_vendor = 'VirtualBox'
        elif output.find('VMware') != -1:
            self.graphics_vendor = 'VMware'
        else:
            self.graphics_vendor = 'Unknown'

        self.graphics_grep = repr(output)
        self.graphics_grep = self.graphics_grep.split("controller: ", 1)
        if len(self.graphics_grep) >= 2:
            self.graphics_grep = self.graphics_grep[1]
            self.graphics_grep = self.graphics_grep.split("\\n", 1)[0]
        else:
            self.graphics_grep = "Unknown"
        dbg.stdout('Specs', 'Detected: ' + str(self.graphics_grep), 1, 2)

    # Collect basic system information
    def run_external_command(self, command, with_shell=False):
        if with_shell:
            raw = str(subprocess.Popen(
                command, stdout=subprocess.PIPE, shell=True).communicate()[0])
        else:
            raw = str(subprocess.Popen(
                command, stdout=subprocess.PIPE).communicate()[0])
        output = raw.replace("b'", "").replace(
            'b"', "").replace("\\n'", "").replace("\\n", "")
        return output

    def create_category_page(self, webkit, category_name):
        dbg.stdout('CategoryInit', 'Criação da página de categorias', 1, 0)

        metadata = '/usr/share/policorp-linux-store/data/config/metadata.json'
        with open(metadata, 'r', encoding='utf-8') as file:
            data = json.load(file)

        filtered_packages = [package for package in data['packages'] if package['category'] == category_name]

        html_string  = '<div class="row mt-3 mb-4">'
        if category_name == "Development":
            app.last_page = '"category.html", { category: "Development" }'
            html_string += '<div class="col-md-1 d-flex align-items-center text-md-right">'
            html_string += '<span class="btn-icon material-icons w-100" style="font-size: 64px;">code</span>'
            html_string += '</div>'
            html_string += '<div class="col-md-2 d-flex align-items-center text-md-right">'
            html_string += '<h2 class="mt-2 mb-2"><strong>Desenvolvimento</strong></h2>'
            html_string += '</div>'
        elif category_name == "Games":
            app.last_page = '"category.html", { category: "Games" }'
            html_string += '<div class="col-md-1 d-flex align-items-center text-md-right">'
            html_string += '<span class="btn-icon material-icons w-100" style="font-size: 64px;">videogame_asset</span>'
            html_string += '</div>'
            html_string += '<div class="col-md-2 d-flex align-items-center text-md-right">'
            html_string += '<h2 class="mt-2 mb-2"><strong>Jogos</strong></h2>'
            html_string += '</div>'
        elif category_name == "Internet":
            app.last_page = '"category.html", { category: "Internet" }'
            html_string += '<div class="col-md-1 d-flex align-items-center text-md-right">'
            html_string += '<span class="btn-icon material-icons w-100" style="font-size: 64px;">public</span>'
            html_string += '</div>'
            html_string += '<div class="col-md-2 d-flex align-items-center text-md-right">'
            html_string += '<h2 class="mt-2 mb-2"><strong>Internet</strong></h2>'
            html_string += '</div>'
        elif category_name == "Productivity":
            app.last_page = '"category.html", { category: "Productivity" }'
            html_string += '<div class="col-md-1 d-flex align-items-center text-md-right">'
            html_string += '<span class="btn-icon material-icons w-100" style="font-size: 64px;">flash_on</span>'
            html_string += '</div>'
            html_string += '<div class="col-md-2 d-flex align-items-center text-md-right">'
            html_string += '<h2 class="mt-2 mb-2"><strong>Produtividade</strong></h2>'
            html_string += '</div>'
        else:
            #TODO - Chamar loja padrão do sistema
            pass
        html_string += '</div>'

        html_string  += '<div class="row mt-3 mb-3">'
        for package in filtered_packages:
            html_string += '<div class="col-md-3 text-md-center mb-3">'
            html_string += '<div class="card rounded card-menu-1 shadow bg-light" '
            html_string += f'onclick="openApp(\'{package["name"]}\');">'
            html_string += '<div class="card-body card-menu-body">'
            html_string += '<div class="row">'
            html_string += '<div class="col-md-4 text-md-center">'
            html_string += f'<img class="rounded w-100" src="img/applications/{package["category"]}/{package["icon"]}">'
            html_string += '</div>'
            html_string += '<div class="col-md-8 d-flex align-items-center text-md-left">'
            html_string += f'<p class="mt-3"><strong>{package["name"]}</strong></p>'
            html_string += '</div>'
            html_string += '</div>'
            html_string += '</div>'
            html_string += '</div>'
            html_string += '</div>'
        html_string += '</div>'

        app.update_page('#content', 'append', html_string)
        
        app.run_javascript('setCursorNormal();')

    def create_app_page(self, webkit):
        dbg.stdout('AppInit', 'Criação da página de app', 1, 0)

        self.remove_control_file()
        if not codecmanager.isCodecInstalled():
            app.run_javascript(f"$('#btn_install_app').removeClass('d-none');")
            app.run_javascript(f"$('#btn_install_app').addClass('d-block');")
        else:
            app.run_javascript("document.getElementById('btn_remove_app').classList.remove('d-none');")
            app.run_javascript("document.getElementById('btn_remove_app').classList.add('d-block');")

        app.run_javascript(f"$('#lbl_name_app strong').text('Multimídia Codecs');")
        app.run_javascript(f"$('#lbl_description_app').text('Para total funcionalidade de alguns sons e videos é necessário a adição de codecs específicos');")

        app.run_javascript(f"$('#img_app').attr('src', 'img/codec-icon.png');")
        
        app.run_javascript('setCursorNormal();')


class StoreApp(object):

    def __init__(self):
        self.current_page = ""
        self.last_page = ""

        # establish our location
        self._location = os.path.dirname(
            os.path.abspath(inspect.getfile(inspect.currentframe())))

        global start_location
        # check for relative path
        if (os.path.exists(os.path.join(self._location, 'data/'))):
            self._data_path = os.path.join(self._location, 'data/')
            start_location = self._location + "/"
        else:
            print('Unable to source the store data directory.')
            sys.exit(1)

        self._start_page = os.path.join(self._data_path, 'index.html')

        self._build_app()

    def get_screen_resolution(self):
        screen = Gdk.Screen.get_default()
        width = screen.get_width()
        height = screen.get_height()
        return width, height

    def _get_resolution(self):
        width, height = self.get_screen_resolution()
        return (width, height)
        
    def _build_app(self):
        # Load custom css for App
        # self._load_css()

        # build window
        w = Gtk.Window()
        w.set_position(Gtk.WindowPosition.CENTER)
        w.set_title("Instalador de Codecs Multimídia")

        icon_dir = os.path.join(self._data_path, 'img', 'store', 'codec-icon.png')
        w.set_icon_from_file(icon_dir)

        # Turn window into a CSD styled application and create menu entries.
        header = Gtk.HeaderBar(title="Instalador de Codecs Multimídia")
        header.props.show_close_button = True
        w.set_titlebar(header)

        section_label = Gtk.Label()
        page_title = Gtk.Label()

        theme = Gtk.IconTheme.get_default()
        theme.append_search_path(os.path.join(self._data_path, 'img', 'store'))
        iconfile =  Gio.ThemedIcon(name="icon")
        about_img = Gtk.Image.new_from_gicon(iconfile,Gtk.IconSize.DND)

        about_btn = Gtk.Button(image=about_img)
        about_btn.set_name("about-btn")
        about_btn.set_can_focus(False)

        header.pack_start(page_title)

        # build webkit container
        mv = AppView()
        width, height = self._get_resolution()

        dbg.stdout('Resolution', "width " + str(width) + " height " + str(height), 0, 0)
        if width >= 1280:
            w.set_default_size(890, 600)
            mv.set_zoom_level(0.64)
        elif width <= 900:
            w.set_default_size(690, 500)
            mv.set_zoom_level(0.5)
        else:
            w.set_default_size(890, 600)
            mv.set_zoom_level(0.64)

        mv.page_title = page_title

        about_btn.connect("clicked", self._show_about)

        # load our index file
        file = os.path.abspath(os.path.join(
            "data", self._start_page))
        uri = 'file://' + urllib.request.pathname2url(file)
        mv.load_uri(uri)

        # build scrolled window widget and add our appview container
        sw = Gtk.ScrolledWindow()
        sw.set_policy(Gtk.PolicyType.NEVER, Gtk.PolicyType.AUTOMATIC)
        sw.add(mv)

        # build a an autoexpanding box and add our scrolled window
        b = Gtk.Box(homogeneous=False, spacing=0)
        b.pack_start(sw, expand=True, fill=True, padding=0)

        # add the box to the parent window and show
        w.add(b)
        w.connect('delete-event', self.close)
        w.show_all()

        self._window = w
        win = w
        self.webkit = mv

    def run(self):
        signal.signal(signal.SIGINT, signal.SIG_DFL)
        Gtk.main()

    def _load_css(self):
        '''
            Load custom css to make application consistent with embedded
            web pages
        '''
        style_provider = Gtk.CssProvider()
        style_file = Gio.File.new_for_path(
            os.path.join(self._data_path, 'css', 'app.css'))
        style_provider.load_from_file(style_file)

        Gtk.StyleContext.add_provider_for_screen(
            Gdk.Screen.get_default(),
            style_provider,
            Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION
        )

    def _show_about(self, gtk_widget):
        self.webkit._do_command("about")

    def _show_status(self, gtk_widget):
        self.webkit._do_command("status")

    def close(self, p1=None, p2=None):
        if systemstate.check_control_file_exists():
            message = "<div class=\"text-md-center\">"
            message += "<strong>Codec-Multimídia</strong><br>"
            message += "<br><br> Atenção"
            message += "<br><br>Um processo está em execução no momento. Por favor, espere até que ele seja concluído antes de fechar ou sair."
            message += "</div>"

            popup = PopupMessage(message, PopupMessage.INFO)

            popup.showMessage()
            return True
        else:
            Gtk.main_quit(p1, p2)

    def update_page(self, element, function, parm1=None, parm2=None):
        """ Runs a JavaScript jQuery function on the page,
            ensuring correctly parsed quotes. """
        if parm1 and parm2:
            self.run_javascript(
                '$("' + element + '").' + function + "('" + parm1.replace("'", '\\\'') + "', '" + parm2.replace("'",
                                                                                                                '\\\'') + "')")
        if parm1:
            self.run_javascript(
                '$("' + element + '").' + function + "('" + parm1.replace("'", '\\\'') + "')")
        else:
            self.run_javascript('$("' + element + '").' + function + '()')

    def run_javascript(self, script):
        """
        Runs a JavaScript function on the page, regardless of which thread it is called from.
        GTK+ operations must be performed on the same thread to prevent crashes.
        """
        GLib.idle_add(self._run_javascript, script)

    def _run_javascript(self, script):
        """
        Runs a JavaScript script on the page when invoked from run_javascript()
        """
        self.webkit.evaluate_javascript(script, -1, None, None, None, None)
        return GLib.SOURCE_REMOVE


if __name__ == "__main__":
    # Process any parameters passed to the program.
    dbg = Debug()

    codecmanager = CodecManager()

    systemstate = SystemState()

    app = StoreApp()
    app.run()
